name: llamacpp
description: local llama2
version: 2.2.0

# https://code.pieces.app/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  ffi: ^1.1.2
  dynamic_library: ^0.8.0
  system_info2: ^3.0.2

dev_dependencies:
  test: ^1.17.2
  runtime_lints: ^0.3.0
